{% set name = "igwn-robot-auth" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/igwn_robot_auth-{{ version }}.tar.gz
  sha256: ba5602262c229bad4dcca8d7d5c7421797daed7465f00b92738c6096782c85c9

build:
  entry_points:
    - igwn-robot-get = igwn_robot_auth.tools.get:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=70.0.0
    - setuptools-scm >=3.4.3
    - wheel
  run:
    - python >={{ python_min }}
    - python-htcondor
    - igwn-auth-utils >=1.3.0

test:
  requires:
    - pip
    - pytest >=3.9.1
    - python {{ python_min }}
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show igwn-robot-auth
    # run test suite
    - python -m pytest --pyargs igwn_robot_auth.tests
    # check entry points
    - igwn-robot-get --help

about:
  summary: Auth credential management for IGWN robots
  description: |
    Utilities for managing authentication and authorisation for
    IGWN unattended (robot) processes.
  home: https://git.ligo.org/computing/software/igwn-robot-auth
  doc_url: https://computing.docs.ligo.org/software/igwn-robot-auth/
  dev_url: https://git.ligo.org/computing/software/igwn-robot-auth.git
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
